project_id = "dwxrdgimwuhlcjsdugzu"

[functions.analyze-expenses]
verify_jwt = true

[functions.analytics-chatbot]
verify_jwt = true

[functions.extract-receipt-ocr]
verify_jwt = false

[functions.send-expense-email]
verify_jwt = false

[functions.send-gmail-expense]
verify_jwt = true

[functions.schedule-expense-emails]
verify_jwt = false

[functions.verify-expense-token]
verify_jwt = false

[functions.send-waitlist-notification]
verify_jwt = false

[functions.export-tally-xml]
verify_jwt = true

[functions.export-quickbooks-iif]
verify_jwt = true

[functions.export-zoho-csv]
verify_jwt = true

[functions.generate-calendar-ics]
verify_jwt = true